
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class FGrupos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FUsuarios.class.getName());
    //----------------------------------------------------------------------------------//
    String url = "http://whatsappweb.webcindario.com/mysql.php";
    ConexionHR cnx = new ConexionHR(url);

        
    String gruposg = "SELECT nombreg, descripcion, fecha_creacion FROM grupos ORDER BY nombreg ";

    String niveles = "SELECT DATE_FORMAT(fecha_creacion, '%M %Y') as mes, COUNT(*) as total "
            + "FROM grupos "
            + "ORDER BY fecha_creacion ASC ";
    String grupo = "GROUP BY DATE_FORMAT(fecha_creacion, '%Y-%m') ";
    //----------------------------------------------------------------------------------//

    public FGrupos() {
        initComponents();

        setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PTitulo = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PFormulario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TFDesc = new javax.swing.JTextField();
        TFIdG = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TFecha = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TUsuarios = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        BOrdenar = new javax.swing.JButton();
        BNuevo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        BAgregar = new javax.swing.JButton();
        BActualizar = new javax.swing.JButton();
        BBorrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        BPdf = new javax.swing.JButton();
        BGrafica = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jLabel3 = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jLabel6 = new javax.swing.JLabel();
        TFNumero = new javax.swing.JTextField();
        BBuscarAlumnos = new javax.swing.JButton();
        PFondo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PTitulo.setBackground(new java.awt.Color(0, 0, 51));
        PTitulo.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 153, 255));
        jLabel11.setText("GRUPOS");
        PTitulo.add(jLabel11);
        jLabel11.setBounds(40, 20, 250, 40);
        PTitulo.add(jLabel8);
        jLabel8.setBounds(19, 17, 0, 60);
        PTitulo.add(jLabel10);
        jLabel10.setBounds(0, 0, 1120, 90);

        PFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Paciente:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(78, 80, 82));
        jLabel1.setText("NOMBRE");

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(78, 80, 82));
        jLabel2.setText("DESCRIPCION");

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(78, 80, 82));
        jLabel5.setText("FECHA");

        javax.swing.GroupLayout PFormularioLayout = new javax.swing.GroupLayout(PFormulario);
        PFormulario.setLayout(PFormularioLayout);
        PFormularioLayout.setHorizontalGroup(
            PFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PFormularioLayout.createSequentialGroup()
                .addGroup(PFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PFormularioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PFormularioLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(PFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(PFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFIdG, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        PFormularioLayout.setVerticalGroup(
            PFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PFormularioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFIdG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135))
        );

        TUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TUsuariosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(TUsuarios);

        jToolBar1.setRollover(true);

        BOrdenar.setText("ORDENAR");
        BOrdenar.setFocusable(false);
        BOrdenar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BOrdenar.setMaximumSize(new java.awt.Dimension(100, 70));
        BOrdenar.setMinimumSize(new java.awt.Dimension(100, 70));
        BOrdenar.setPreferredSize(new java.awt.Dimension(100, 70));
        BOrdenar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOrdenarActionPerformed(evt);
            }
        });
        jToolBar1.add(BOrdenar);

        BNuevo.setText("NUEVO");
        BNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BNuevo.setMaximumSize(new java.awt.Dimension(100, 70));
        BNuevo.setMinimumSize(new java.awt.Dimension(100, 70));
        BNuevo.setPreferredSize(new java.awt.Dimension(100, 70));
        BNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(BNuevo);
        jToolBar1.add(jSeparator2);

        BAgregar.setText("AGREGAR");
        BAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BAgregar.setMaximumSize(new java.awt.Dimension(100, 70));
        BAgregar.setMinimumSize(new java.awt.Dimension(100, 70));
        BAgregar.setPreferredSize(new java.awt.Dimension(100, 70));
        BAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAgregarActionPerformed(evt);
            }
        });
        jToolBar1.add(BAgregar);

        BActualizar.setText("ACTUALIZAR");
        BActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BActualizar.setMaximumSize(new java.awt.Dimension(100, 70));
        BActualizar.setMinimumSize(new java.awt.Dimension(100, 70));
        BActualizar.setPreferredSize(new java.awt.Dimension(100, 70));
        BActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(BActualizar);

        BBorrar.setText("BORRAR");
        BBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BBorrar.setMaximumSize(new java.awt.Dimension(100, 70));
        BBorrar.setMinimumSize(new java.awt.Dimension(100, 70));
        BBorrar.setPreferredSize(new java.awt.Dimension(100, 70));
        BBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrarActionPerformed(evt);
            }
        });
        jToolBar1.add(BBorrar);
        jToolBar1.add(jSeparator1);

        BPdf.setText("PDF");
        BPdf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BPdf.setMaximumSize(new java.awt.Dimension(100, 70));
        BPdf.setMinimumSize(new java.awt.Dimension(100, 70));
        BPdf.setPreferredSize(new java.awt.Dimension(100, 70));
        BPdf.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPdfActionPerformed(evt);
            }
        });
        jToolBar1.add(BPdf);

        BGrafica.setText("GRAFICA");
        BGrafica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BGrafica.setMaximumSize(new java.awt.Dimension(100, 70));
        BGrafica.setMinimumSize(new java.awt.Dimension(100, 70));
        BGrafica.setPreferredSize(new java.awt.Dimension(100, 70));
        BGrafica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGraficaActionPerformed(evt);
            }
        });
        jToolBar1.add(BGrafica);
        jToolBar1.add(jSeparator3);

        jLabel3.setText("NOMBRE");
        jToolBar1.add(jLabel3);

        TFNombre.setMaximumSize(new java.awt.Dimension(150, 50));
        TFNombre.setMinimumSize(new java.awt.Dimension(150, 50));
        TFNombre.setPreferredSize(new java.awt.Dimension(150, 50));
        jToolBar1.add(TFNombre);
        jToolBar1.add(jSeparator4);

        jLabel6.setText("TELEFONO");
        jToolBar1.add(jLabel6);

        TFNumero.setMaximumSize(new java.awt.Dimension(150, 50));
        TFNumero.setMinimumSize(new java.awt.Dimension(150, 50));
        TFNumero.setPreferredSize(new java.awt.Dimension(150, 50));
        jToolBar1.add(TFNumero);

        BBuscarAlumnos.setText("BUSCAR");
        BBuscarAlumnos.setFocusable(false);
        BBuscarAlumnos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BBuscarAlumnos.setMaximumSize(new java.awt.Dimension(100, 70));
        BBuscarAlumnos.setMinimumSize(new java.awt.Dimension(100, 70));
        BBuscarAlumnos.setPreferredSize(new java.awt.Dimension(100, 70));
        BBuscarAlumnos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BBuscarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarAlumnosActionPerformed(evt);
            }
        });
        jToolBar1.add(BBuscarAlumnos);

        PFondo.setBackground(new java.awt.Color(255, 255, 204));
        PFondo.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1215, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TUsuariosMousePressed
        DefaultTableModel datos = (DefaultTableModel) TUsuarios.getModel();
        int renSel = TUsuarios.getSelectedRow();

        if (renSel > -1) {
            String id = datos.getValueAt(renSel, 0).toString();
            String nom = datos.getValueAt(renSel, 1).toString();
            String fec = datos.getValueAt(renSel, 2).toString();

            TFIdG.setText(id);
            TFDesc.setText(nom);
            TFecha.setText(fec);

        }
    }//GEN-LAST:event_TUsuariosMousePressed

    private void BOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOrdenarActionPerformed
        String sql = "SELECT nombreg, descripcion, fecha_creacion "
                + "FROM grupos "
                + "ORDER BY nombreg ";

        cnx.entablar(sql, TUsuarios);
    }//GEN-LAST:event_BOrdenarActionPerformed

    private void BNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevoActionPerformed
        TFIdG.setText("");
        TFDesc.setText("");
        TFecha.setText("");
    }//GEN-LAST:event_BNuevoActionPerformed

    private void BAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregarActionPerformed
        String id = TFIdG.getText().trim();
        String nom = TFDesc.getText().trim();
        String fec = TFecha.getText().trim();

        if (id.isEmpty() || nom.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "ID y Nombre son obligatorios.",
                    "Datos incompletos",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int ok = insertarGruposAPI(id, nom, fec);

        if (ok == 1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Grupo agregado correctamente.",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Recargar la tabla de alumnos
            String consulta = "SELECT nombreg, descripcion, fecha_creacion FROM grupos ORDER BY nombreg";
            cnx.entablar(consulta, TUsuarios);

        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo agregar el grupo. Revisa la consola (RESPUESTA API).",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BAgregarActionPerformed

    private void BActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActualizarActionPerformed
        String id = TFIdG.getText();
        String nom = TFDesc.getText();
        String num = TFecha.getText().trim();

        String[] valores = new String[]{id, nom, num};

        cnx.actualizar("grupos", valores);
        cnx.entablar(grupo, TUsuarios);
    }//GEN-LAST:event_BActualizarActionPerformed

    private void BBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrarActionPerformed
        String id = TFIdG.getText();
        String nom = TFDesc.getText();
        String num = TFecha.getText().trim();

        String[] valores = new String[]{id, nom, num};

        cnx.borrar("grupos", valores);
        cnx.entablar(num, TUsuarios);
    }//GEN-LAST:event_BBorrarActionPerformed

    private void BPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPdfActionPerformed
         String id = TFIdG.getText();
        String query = niveles + "WHERE nombreg = '" + id + "' " + grupo;

        int ok = cnx.crearPDF("Grupo", "Promedio Mensual de Grupos",
                query, new float[]{0.5f, 0.5f}, "promedio_grupos");

        if (ok == 1) {
            cnx.visualizarPDF("promedio_grupos");

        } else {
            System.out.println("PDF no generado");
        
        }
    }//GEN-LAST:event_BPdfActionPerformed

    private void BGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGraficaActionPerformed
        String id = TFIdG.getText();
        String query = niveles + "WHERE nombreg = '" + id + "' " + grupo;

        ArrayList<String> series = new ArrayList();
        ArrayList<ArrayList<String>> datos = new ArrayList();

        datos = cnx.consultar(query);

        series.add(id);

        GraficaXY graf = new GraficaXY("clasificacion por iniciales", "letras", "Promedio", series, datos);

        PFondo.removeAll();
        PFondo.add(graf.chartPanel);
        PFondo.updateUI();
    }//GEN-LAST:event_BGraficaActionPerformed

    private void BBuscarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarAlumnosActionPerformed
        String nombreg = TFNombre.getText().trim();
        String descripcion = TFNumero.getText().trim();

        String sql = "SELECT nombreg, descripcion, fecha_creacion "
                + "FROM grupos WHERE 1=1 ";

        if (!nombreg.isEmpty()) {
            sql += " AND nombreg LIKE '%" + nombreg + "%' ";
        }
        if (!descripcion.isEmpty()) {
            sql += " AND descripcion LIKE '%" + descripcion + "%' ";
        }

        sql += " ORDER BY nombreg ";

        cnx.entablar(sql, TUsuarios);
    }//GEN-LAST:event_BBuscarAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FUsuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BActualizar;
    private javax.swing.JButton BAgregar;
    private javax.swing.JButton BBorrar;
    private javax.swing.JButton BBuscarAlumnos;
    private javax.swing.JButton BGrafica;
    private javax.swing.JButton BNuevo;
    private javax.swing.JButton BOrdenar;
    private javax.swing.JButton BPdf;
    private javax.swing.JPanel PFondo;
    private javax.swing.JPanel PFormulario;
    private javax.swing.JPanel PTitulo;
    private javax.swing.JTextField TFDesc;
    private javax.swing.JTextField TFIdG;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTextField TFNumero;
    private javax.swing.JTextField TFecha;
    private javax.swing.JTable TUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    public int insertarGruposAPI(
            String nombreg, String descripcion,
            String fechac) {

        try {
            System.out.println("DEBUG insertarGrupoAPI() ********");
            System.out.println("id=" + nombreg);
            System.out.println("nombre=" + descripcion);
            System.out.println("fecha=" + fechac);

            StringBuilder postData = new StringBuilder();

            String[][] params = {
                {"key", "secret"},
                {"accion", "insertGrupo"},
                {"nombreg", nombreg},
                {"descripcion", descripcion},
                {"fecha_creacion", fechac}
            };

            for (int i = 0; i < params.length; i++) {
                if (i > 0) {
                    postData.append('&');
                }
                postData.append(java.net.URLEncoder.encode(params[i][0], "UTF-8"));
                postData.append('=');
                postData.append(java.net.URLEncoder.encode(
                        params[i][1] == null ? "" : params[i][1], "UTF-8"));
            }

            byte[] postBytes = postData.toString().getBytes("UTF-8");

            java.net.URL u = new java.net.URL("http://usuariosgrupos.webcindario.com/api_grupos.php");
            java.net.HttpURLConnection conn = (java.net.HttpURLConnection) u.openConnection();
            conn.setDoOutput(true);
            conn.setRequestMethod("POST");
            conn.setRequestProperty("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8");
            conn.getOutputStream().write(postBytes);

            java.io.InputStream is = conn.getInputStream();
            java.util.Scanner s = new java.util.Scanner(is, "UTF-8").useDelimiter("\\A");
            String respuesta = s.hasNext() ? s.next() : "";
            System.out.println("RESPUESTA API: [" + respuesta + "]");

            return respuesta.contains("OK") ? 1 : 0;

        } catch (Exception e) {
            System.out.println("Error API insertGrupo: " + e.getMessage());
            e.printStackTrace(); // para ver el detalle exacto
            return 0;
        }
    }
}
